"""
Unit tests for net classification.

Classification is where most of the electronics domain knowledge enters the
pipeline, and every later stage depends on it: if ``GND`` is not recognised as a
rail, the topology projection collapses. These tests therefore cover the naming
conventions found in real designs, the pattern-ordering subtlety that makes
``VSS`` a ground rather than a supply, and the guard on the fanout fallback.
"""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from netlist_topology_analyzer.core.classifier import (  # noqa: E402
    classify_board,
    classify_net,
)
from netlist_topology_analyzer.core.config import AnalysisConfig  # noqa: E402
from netlist_topology_analyzer.core.model import Net, NetRole, Pad  # noqa: E402

from tests.fixtures import mk_board, mk_component  # noqa: E402


def net(name, pads=2, code=1):
    """A net with ``pads`` distinct pad members on distinct components."""
    return Net(
        name=name,
        code=code,
        pads=[Pad(reference="X{0}".format(i), number="1", net_name=name, net_code=code)
              for i in range(pads)],
    )


class TestLeafNetName(unittest.TestCase):
    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_hierarchical_path_is_stripped(self):
        self.assertEqual(self.cfg.leaf_net_name("/power_supply/+3V3"), "+3V3")

    def test_flat_name_untouched(self):
        self.assertEqual(self.cfg.leaf_net_name("SDA"), "SDA")

    def test_kicad_autogenerated_name_untouched(self):
        # "Net-(U1-Pad3)" contains no slash to strip, and must not be mangled.
        self.assertEqual(self.cfg.leaf_net_name("Net-(U1-Pad3)"), "Net-(U1-Pad3)")

    def test_empty(self):
        self.assertEqual(self.cfg.leaf_net_name(""), "")

    def test_whitespace_is_trimmed(self):
        self.assertEqual(self.cfg.leaf_net_name("  GND  "), "GND")


class TestGroundRecognition(unittest.TestCase):
    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_common_ground_names(self):
        for name in ("GND", "GNDA", "AGND", "DGND", "PGND", "GND_1", "VSS",
                     "VSSA", "0V", "EARTH", "CHASSIS_GND", "VEE",
                     "ANALOG_GROUND"):
            self.assertEqual(
                classify_net(net(name), self.cfg), NetRole.GROUND,
                "{0} should classify as GROUND".format(name),
            )

    def test_case_insensitive(self):
        self.assertEqual(classify_net(net("gnd"), self.cfg), NetRole.GROUND)

    def test_hierarchical_ground(self):
        self.assertEqual(classify_net(net("/analog/AGND"), self.cfg), NetRole.GROUND)


class TestPowerRecognition(unittest.TestCase):
    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_common_power_names(self):
        for name in ("VCC", "VCCIO", "VDD", "VDDA", "AVDD", "DVDD", "VBUS",
                     "VBAT", "VIN", "VOUT", "VREF", "3V3", "+3V3", "+5V",
                     "12V", "-12V", "V3V3", "P3V3", "+3V3_MCU", "PWR_IN",
                     "RAIL_A"):
            self.assertEqual(
                classify_net(net(name), self.cfg), NetRole.POWER,
                "{0} should classify as POWER".format(name),
            )

    def test_hierarchical_power(self):
        self.assertEqual(classify_net(net("/power/+3V3"), self.cfg), NetRole.POWER)


class TestPatternOrdering(unittest.TestCase):
    """Ground must be tested before power, or ``V...`` swallows ``VSS``."""

    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_vss_is_ground_not_power(self):
        self.assertEqual(classify_net(net("VSS"), self.cfg), NetRole.GROUND)

    def test_vssa_is_ground(self):
        self.assertEqual(classify_net(net("VSSA"), self.cfg), NetRole.GROUND)

    def test_vee_is_ground(self):
        self.assertEqual(classify_net(net("VEE"), self.cfg), NetRole.GROUND)

    def test_vdd_is_still_power(self):
        self.assertEqual(classify_net(net("VDD"), self.cfg), NetRole.POWER)


class TestSignalAndUnconnected(unittest.TestCase):
    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_ordinary_signal_names(self):
        for name in ("SDA", "SCL", "UART_TX", "SPI_MISO", "RESET", "Net-(U1-Pad3)",
                     "CLK", "D0"):
            self.assertEqual(
                classify_net(net(name), self.cfg), NetRole.SIGNAL,
                "{0} should classify as SIGNAL".format(name),
            )

    def test_empty_name_is_unconnected(self):
        self.assertEqual(classify_net(net(""), self.cfg), NetRole.UNCONNECTED)

    def test_net_with_no_pads_is_unconnected(self):
        self.assertEqual(classify_net(Net(name="SDA", code=1), self.cfg),
                         NetRole.UNCONNECTED)

    def test_kicad_unconnected_prefix(self):
        for name in ("unconnected-(U1-Pad7)", "Net-(unconnected-U2-Pad3)"):
            self.assertEqual(classify_net(net(name), self.cfg), NetRole.UNCONNECTED)

    def test_single_pad_net_is_still_a_signal(self):
        # Reported separately by the floating-net analyzer; hiding it here would
        # lose the finding.
        self.assertEqual(classify_net(net("TP_SPARE", pads=1), self.cfg),
                         NetRole.SIGNAL)


class TestFanoutFallback(unittest.TestCase):
    """A net reaching most components is a rail whatever it is called."""

    def setUp(self):
        self.cfg = AnalysisConfig()

    def test_wide_net_on_a_large_board_is_inferred_as_power(self):
        # 10 components, net touches 8 of them: 8 >= round(0.60 * 10) = 6.
        self.assertEqual(
            classify_net(net("MAIN_SUPPLY", pads=8), self.cfg, component_count=10),
            NetRole.POWER,
        )

    def test_narrow_net_on_a_large_board_stays_a_signal(self):
        self.assertEqual(
            classify_net(net("BUS_A", pads=3), self.cfg, component_count=10),
            NetRole.SIGNAL,
        )

    def test_heuristic_is_gated_on_board_size(self):
        # On a 4-component board every net looks like a rail, so the fallback
        # must not fire at all.
        self.assertEqual(
            classify_net(net("ANYTHING", pads=4), self.cfg, component_count=4),
            NetRole.SIGNAL,
        )

    def test_heuristic_can_be_disabled(self):
        cfg = AnalysisConfig(rail_fanout_ratio=1.5)
        self.assertEqual(
            classify_net(net("MAIN_SUPPLY", pads=20), cfg, component_count=20),
            NetRole.SIGNAL,
        )

    def test_custom_house_style_pattern(self):
        cfg = AnalysisConfig(power_patterns=(r"^SUPPLY",))
        self.assertEqual(classify_net(net("SUPPLY_A"), cfg), NetRole.POWER)
        self.assertEqual(classify_net(net("VCC"), cfg), NetRole.SIGNAL)


class TestClassifyBoard(unittest.TestCase):
    def test_histogram_covers_every_role(self):
        board = mk_board([
            mk_component("U1", [(1, "+3V3"), (2, "GND"), (3, "SDA"), (4, "")]),
            mk_component("C1", [(1, "+3V3"), (2, "GND")]),
        ])
        histogram = classify_board(board, AnalysisConfig())
        self.assertEqual(set(histogram.keys()), set(NetRole.ALL))
        self.assertEqual(histogram[NetRole.POWER], 1)
        self.assertEqual(histogram[NetRole.GROUND], 1)
        self.assertEqual(histogram[NetRole.SIGNAL], 1)

    def test_roles_are_written_back_onto_the_nets(self):
        board = mk_board([mk_component("U1", [(1, "GND"), (2, "SDA")]),
                          mk_component("U2", [(1, "GND"), (2, "SDA")])])
        classify_board(board, AnalysisConfig())
        self.assertEqual(board.net_by_name("GND").role, NetRole.GROUND)
        self.assertEqual(board.net_by_name("SDA").role, NetRole.SIGNAL)

    def test_mechanical_and_dnp_parts_do_not_skew_the_fanout_ratio(self):
        """Mounting holes must not inflate the component count.

        Nine real parts share ``BULK``; adding twenty mounting holes would push
        the ratio below the threshold if they were counted, so ``BULK`` would
        stop being recognised as a rail.
        """
        components = [
            mk_component("R{0}".format(i), [(1, "BULK"), (2, "OUT{0}".format(i))])
            for i in range(9)
        ]
        components += [mk_component("H{0}".format(i), [(1, "")]) for i in range(20)]
        board = mk_board(components)
        classify_board(board, AnalysisConfig())
        self.assertEqual(board.net_by_name("BULK").role, NetRole.POWER)


if __name__ == "__main__":
    unittest.main()
